n1 = int(input('Digite o priemiro número: '))
n2 = int(input('Digite o segundo número: '))
if n1 == n2: print ('Os dois número são iguais')
elif n1 > n2 : print('O número ',n1,' é maior que ', n2,'.')
else: print('O número ', n2,' é maior que ', n1,'.')