import pyautogui
import time

pyautogui.hotkey("win", "r")
time.sleep(1)
pyautogui.write("notepad++")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.hotkey("ctrl", "n")
time.sleep(1)
pyautogui.write("Festa Zumbiii")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("ÔOOoooUUUUUUUOOOooo")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("ja convidei a magrela e os carcas tbm")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.write("aq na Festa Zumbiii")
time.sleep(1)
pyautogui.hotkey("enter")
time.sleep(1)
pyautogui.hotkey("ctrl","alt","s")
time.sleep(1)
pyautogui.write("anotacao.txt")
time.sleep(1)
pyautogui.hotkey("alt","d")
time.sleep(1)
pyautogui.moveTo(x=289, y=111)
time.sleep(1)
pyautogui.leftClick(x=289, y=111)
time.sleep(1)
caminho = ("C:\Users\Tec. Inf - Eddy\Desktop\Aooopa")
pyautogui.write (caminho)
time.sleep(1)
pyautogui.hotkey("enter")
